import {
  Geist,
  Geist_Mono,
  Bokor,
  Anton,
  Roboto,
  Poppins,
  Playfair_Display,
} from "next/font/google";
import "./globals.css";

import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import "react-datepicker/dist/react-datepicker.css";
import { googleFonts } from "@/lib/goggleFonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const fontClasses = Object.values(googleFonts)
//   .map((font) => font.className)
//   .join(" ");

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  `}>
        {children}
      </body>
    </html>
  );
}
