import RenderViewComponent from "@/components/RenderViewComponent";

const publishData = {
  assets: [],
  styles: [],
  pages: [
    {
      frames: [
        {
          component: {
            type: "wrapper",
            stylable: "",
            highlightable: false,
            hoverable: false,
            attributes: {
              id: "i56t",
            },
            components: [
              {
                type: "checkout-form",
                draggable: false,
                attributes: {
                  id: "ilzj",
                },
                customComponent: {
                  contents: [],
                  isShippingRequired: true,
                  isAddressRequired: true,
                  address: {
                    isRequired: true,
                    type: "subdistrict-only",
                  },
                  shipping: {
                    isRequired: true,
                  },
                  paymentMethod: {
                    label: "Metode Pengiriman",
                    isCod: true,
                    isBankTransfer: true,
                    isEpayment: true,
                    isRequired: true,
                    methodOptions: [],
                  },
                  summary: {
                    isRequired: true,
                    label: "Rincian Pembayaran",
                  },
                  recipient: {
                    paymentMethod: {
                      type: "",
                      data: null,
                    },
                    products: [
                      {
                        id: "561d9513-675b-487d-91ca-47cbffab7bea",
                        name: "Test #1",
                        price: 100,
                        quantity: 1,
                      },
                    ],
                  },
                  warehouse: {},
                  products: {
                    selectedProducts: [
                      {
                        id: "561d9513-675b-487d-91ca-47cbffab7bea",
                        name: "Test #1",
                        description: "Test #1",
                        subdomain_product: "test-1",
                        price: 100,
                        weight: 100,
                        min_order: 1,
                        status: "inactive",
                        is_empty: false,
                        condition: "Baru",
                        is_promoted: false,
                        due_promoted: null,
                        category_id: 2,
                        showcase_id: 2,
                        store_id: 2,
                        is_visible: false,
                        is_deleted: false,
                        updatedAt: "2024-04-22T03:15:25.493Z",
                        createdAt: "2018-04-27T02:58:28.782Z",
                        GrocierPrices: [
                          {
                            id: 922,
                            min_order: 20,
                            price: 98,
                            cashback: 6,
                          },
                          {
                            id: 921,
                            min_order: 10,
                            price: 99,
                            cashback: 5,
                          },
                        ],
                        ProductSold: null,
                        ProductViews: [
                          {
                            id: 94,
                            user_id: 2,
                          },
                          {
                            id: 13,
                            user_id: 3,
                          },
                        ],
                        ProductVolume: null,
                        ImageProducts: [
                          {
                            id: "c4f24bb3-a288-41c1-a9e3-f554cf90896a",
                            url: "https://image-plasgos.s3.ap-southeast-1.amazonaws.com/product/1547110466108_wallpaper1491892286e618c9.jpg",
                            is_default: false,
                            square_200_url:
                              "https://image-cache-plasgos.s3.amazonaws.com/p/cache/200-square/2021/1/19/c4f24bb3-a288-41c1-a9e3-f554cf90896a.jpg",
                            square_300_url:
                              "https://image-cache-plasgos.s3.amazonaws.com/p/cache/300-square/2021/1/19/c4f24bb3-a288-41c1-a9e3-f554cf90896a.jpg",
                          },
                          {
                            id: "ef0c0feb-36ef-4dd5-8713-c9b3900a7e1f",
                            url: "https://image-plasgos.s3.amazonaws.com/product/1538982230516_1524797909382_1303247_2505060b-16d0-4b78-8031-fa0ad1cb2a5a.png",
                            is_default: true,
                            square_200_url:
                              "https://image-cache-plasgos.s3.amazonaws.com/p/cache/200-square/2021/1/19/ef0c0feb-36ef-4dd5-8713-c9b3900a7e1f.png",
                            square_300_url:
                              "https://image-cache-plasgos.s3.amazonaws.com/p/cache/300-square/2021/1/19/ef0c0feb-36ef-4dd5-8713-c9b3900a7e1f.png",
                          },
                        ],
                        Store: {
                          id: 2,
                          name: "Admin ",
                          description: "Admin Shop penjualan",
                          subdomain_store: "admin-test",
                          avatar_img:
                            "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-store/default.png",
                          established_year: "2018",
                          business_type: "Importer",
                          number_of_employee: "1-5",
                          is_premium: false,
                          address: "Graha Mas Pemuda Blok A No 11, Jati",
                          latitude: null,
                          longitude: null,
                          postal_code: "13220",
                          due_premium: null,
                          status: "Open",
                          close_from_date: "2018-12-01T17:00:00.000Z",
                          close_to_date: "2019-07-30T17:00:00.000Z",
                          reason_closed: "tutup",
                          user_id: 2,
                          updatedAt: "2025-06-25T04:44:14.206Z",
                          createdAt: "2018-04-27T02:56:58.749Z",
                          city_id: 154,
                          province_id: 6,
                          subdistrict_id: 2122,
                          Province: {
                            id: 6,
                            name: "DKI Jakarta",
                          },
                          City: {
                            id: 154,
                            name: "Jakarta Timur",
                            type: "Kota",
                          },
                          Subdistrict: {
                            id: 2122,
                            name: "Pulo Gadung",
                            type: "Kecamatan",
                            City: {
                              id: 154,
                              name: "Jakarta Timur",
                              type: "Kota",
                              Province: {
                                id: 6,
                                name: "DKI Jakarta",
                              },
                            },
                          },
                          User: {
                            phone_number: "081283598039",
                          },
                        },
                        Category: {
                          id: 2,
                          name: "Buku",
                          url: "/c/buku",
                        },
                        Showcase: {
                          id: 2,
                          name: "Testing",
                        },
                        Points: [
                          {
                            id: "bacdcdc7-c3d5-4984-bbbe-ecd9e266ef78",
                            review: "Test Point 2",
                            point: 4,
                            is_review: true,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 3,
                            createdAt: "2018-04-27T04:10:00.637Z",
                            updatedAt: "2018-04-27T04:10:43.204Z",
                            User: {
                              name: "Dyan Kastutara",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "68d4419d-76d9-4bea-9cc7-e9754fc3a722",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 3,
                            createdAt: "2018-12-04T09:27:36.637Z",
                            updatedAt: "2018-12-04T09:27:36.637Z",
                            User: {
                              name: "Dyan Kastutara",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "f818dab5-a19f-4d40-925a-010d123d985e",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-04T03:33:16.425Z",
                            updatedAt: "2018-07-04T03:33:16.425Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "2b3a8bbe-1e3a-43b5-8ae7-9bef60b8de95",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-04T03:43:47.121Z",
                            updatedAt: "2018-07-04T03:43:47.121Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "084cf19a-77a3-4d33-926f-cfc6395cb16d",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-04T03:55:20.368Z",
                            updatedAt: "2018-07-04T03:55:20.368Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "cfffc033-1f51-45d7-82f5-a119252a796d",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-03T06:27:35.146Z",
                            updatedAt: "2018-07-03T06:27:35.146Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "aaaea321-c9ea-4ad1-830f-56bf5576ada1",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-03T06:54:51.081Z",
                            updatedAt: "2018-07-03T06:54:51.081Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "9d8d0fc8-acac-48ab-86f4-00f37d757843",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-03T09:26:40.781Z",
                            updatedAt: "2018-07-03T09:26:40.781Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "85583ab3-22d6-41c0-98ab-458f9893aea2",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-03T09:50:38.964Z",
                            updatedAt: "2018-07-03T09:50:38.964Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "81ac8b9a-badd-43dd-a7f7-b033536e14c4",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-03T10:23:09.854Z",
                            updatedAt: "2018-07-03T10:23:09.854Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "6f352413-2aea-47d1-a5ca-8f67dab70643",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-07-03T10:27:33.048Z",
                            updatedAt: "2018-07-03T10:27:33.048Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "bfdf9b0b-c829-4f7e-ab0f-327a08382643",
                            review: "testing testing",
                            point: 4,
                            is_review: true,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            user_id: 4,
                            createdAt: "2018-09-26T03:56:21.591Z",
                            updatedAt: "2018-09-26T04:01:53.828Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                        ],
                        Discussions: [],
                        Stocks: [
                          {
                            id: 4,
                            warehouse_id: 1,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            qty: 0,
                            Warehouse: {
                              id: 1,
                              name: "Gudang GMP Plasgos",
                              phone_number: "085841410308",
                              address: "Graha Mas Pemuda Blok A No 11, Jati",
                              postal_code: "13220",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2122,
                              is_default: true,
                              store_id: 2,
                              Subdistrict: {
                                id: 2122,
                                name: "Pulo Gadung",
                                type: "Kecamatan",
                                city_id: 154,
                                postal_code: "13240",
                                City: {
                                  id: 154,
                                  name: "Jakarta Timur",
                                  type: "Kota",
                                  postal_code: "13330",
                                  province_id: 6,
                                  Province: {
                                    id: 6,
                                    name: "DKI Jakarta",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2023,
                            warehouse_id: 1,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            qty: 100,
                            Warehouse: {
                              id: 1,
                              name: "Gudang GMP Plasgos",
                              phone_number: "085841410308",
                              address: "Graha Mas Pemuda Blok A No 11, Jati",
                              postal_code: "13220",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2122,
                              is_default: true,
                              store_id: 2,
                              Subdistrict: {
                                id: 2122,
                                name: "Pulo Gadung",
                                type: "Kecamatan",
                                city_id: 154,
                                postal_code: "13240",
                                City: {
                                  id: 154,
                                  name: "Jakarta Timur",
                                  type: "Kota",
                                  postal_code: "13330",
                                  province_id: 6,
                                  Province: {
                                    id: 6,
                                    name: "DKI Jakarta",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2237,
                            warehouse_id: 1044,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            qty: 100,
                            Warehouse: {
                              id: 1044,
                              name: "RANDOM FASHION.ID",
                              phone_number: "6285825684150",
                              address:
                                "Villa tangerang regency 2 blok ab7 no.33, Pasar Kemis, Kabupaten Tangerang, Banten, 15560",
                              postal_code: "15560",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 6287,
                              is_default: false,
                              store_id: 2,
                              Subdistrict: {
                                id: 6287,
                                name: "Pasar Kemis",
                                type: "Kecamatan",
                                city_id: 455,
                                postal_code: "15560",
                                City: {
                                  id: 455,
                                  name: "Tangerang",
                                  type: "Kabupaten",
                                  postal_code: "15914",
                                  province_id: 3,
                                  Province: {
                                    id: 3,
                                    name: "Banten",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2242,
                            warehouse_id: 1045,
                            product_id: "561d9513-675b-487d-91ca-47cbffab7bea",
                            qty: 100,
                            Warehouse: {
                              id: 1045,
                              name: "EL MEDINAH PONTIANAK",
                              phone_number: "081212677691",
                              address:
                                "An. Maria Kompack 97 / Jl. Sei Raya Dalam Komplek Bhayangkara Permai Blok E.1 No.7 (arah punggur bukan srikandi), Kec. Sungai Raya Sei/Sungai Raya, Kubu Raya, Kalimantan Barat",
                              postal_code: "78391",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2918,
                              is_default: false,
                              store_id: 2,
                              Subdistrict: {
                                id: 2918,
                                name: "Sei/Sungai Raya",
                                type: "Kecamatan",
                                city_id: 208,
                                postal_code: "78391",
                                City: {
                                  id: 208,
                                  name: "Kubu Raya",
                                  type: "Kabupaten",
                                  postal_code: "78311",
                                  province_id: 12,
                                  Province: {
                                    id: 12,
                                    name: "Kalimantan Barat",
                                  },
                                },
                              },
                            },
                          },
                        ],
                      },
                      {
                        id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                        name: "Test #2",
                        description: "Test #2",
                        subdomain_product: "test-2",
                        price: 30000,
                        weight: 200,
                        min_order: 1,
                        status: "active",
                        is_empty: false,
                        condition: "Baru",
                        is_promoted: false,
                        due_promoted: null,
                        category_id: 2,
                        showcase_id: 2,
                        store_id: 2,
                        is_visible: true,
                        is_deleted: false,
                        updatedAt: "2024-08-26T10:34:46.692Z",
                        createdAt: "2018-04-27T03:00:54.519Z",
                        GrocierPrices: [],
                        ProductSold: null,
                        ProductViews: [
                          {
                            id: 96,
                            user_id: 2,
                          },
                          {
                            id: 14,
                            user_id: 3,
                          },
                        ],
                        ProductVolume: null,
                        ImageProducts: [
                          {
                            id: "a5bce62a-69ca-4e39-b189-1cc79ac270f6",
                            url: "https://image-plasgos.s3.amazonaws.com/product/1538982520163_1524798055392_book_guide_hero_books.png",
                            is_default: true,
                            square_200_url:
                              "https://image-cache-plasgos.s3.ap-southeast-1.amazonaws.com/p/cache/200-square/2021/1/20/a5bce62a-69ca-4e39-b189-1cc79ac270f6.png",
                            square_300_url:
                              "https://image-cache-plasgos.s3.ap-southeast-1.amazonaws.com/p/cache/300-square/2021/1/20/a5bce62a-69ca-4e39-b189-1cc79ac270f6.png",
                          },
                        ],
                        Store: {
                          id: 2,
                          name: "Admin ",
                          description: "Admin Shop penjualan",
                          subdomain_store: "admin-test",
                          avatar_img:
                            "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-store/default.png",
                          established_year: "2018",
                          business_type: "Importer",
                          number_of_employee: "1-5",
                          is_premium: false,
                          address: "Graha Mas Pemuda Blok A No 11, Jati",
                          latitude: null,
                          longitude: null,
                          postal_code: "13220",
                          due_premium: null,
                          status: "Open",
                          close_from_date: "2018-12-01T17:00:00.000Z",
                          close_to_date: "2019-07-30T17:00:00.000Z",
                          reason_closed: "tutup",
                          user_id: 2,
                          updatedAt: "2025-06-25T04:44:14.206Z",
                          createdAt: "2018-04-27T02:56:58.749Z",
                          city_id: 154,
                          province_id: 6,
                          subdistrict_id: 2122,
                          Province: {
                            id: 6,
                            name: "DKI Jakarta",
                          },
                          City: {
                            id: 154,
                            name: "Jakarta Timur",
                            type: "Kota",
                          },
                          Subdistrict: {
                            id: 2122,
                            name: "Pulo Gadung",
                            type: "Kecamatan",
                            City: {
                              id: 154,
                              name: "Jakarta Timur",
                              type: "Kota",
                              Province: {
                                id: 6,
                                name: "DKI Jakarta",
                              },
                            },
                          },
                          User: {
                            phone_number: "081283598039",
                          },
                        },
                        Category: {
                          id: 2,
                          name: "Buku",
                          url: "/c/buku",
                        },
                        Showcase: {
                          id: 2,
                          name: "Testing",
                        },
                        Points: [
                          {
                            id: "f19dc68b-24fe-4e66-b3ab-9ba5348ecef5",
                            review: "Testing Give Point Product",
                            point: 5,
                            is_review: true,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 3,
                            createdAt: "2018-04-27T03:44:56.112Z",
                            updatedAt: "2018-04-27T04:05:12.983Z",
                            User: {
                              name: "Dyan Kastutara",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "856a6c1b-a79d-406c-8f17-52ab0c6ff37b",
                            review: "Test Point 3",
                            point: 3,
                            is_review: true,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 3,
                            createdAt: "2018-04-27T04:10:00.636Z",
                            updatedAt: "2018-04-27T04:10:52.733Z",
                            User: {
                              name: "Dyan Kastutara",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "d4261942-a712-4c28-b47b-ee213c8f2420",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 3,
                            createdAt: "2018-12-04T09:27:36.637Z",
                            updatedAt: "2018-12-04T09:27:36.637Z",
                            User: {
                              name: "Dyan Kastutara",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "2ffc3daa-1521-474f-9dc3-7537fec94972",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T10:36:54.099Z",
                            updatedAt: "2018-07-03T10:36:54.099Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "05a571ea-b90c-44a1-ab48-35b68e7fc30f",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-04T03:41:55.138Z",
                            updatedAt: "2018-07-04T03:41:55.138Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "2a725d77-7f4a-47cd-b093-e992572ecba6",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-04T03:50:59.110Z",
                            updatedAt: "2018-07-04T03:50:59.110Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "b1138542-11bd-4b4f-83a8-abc6652304a9",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-06-29T09:11:34.173Z",
                            updatedAt: "2018-06-29T09:11:34.173Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "580c367f-34a3-4883-95aa-7382a4fcf407",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T07:17:52.995Z",
                            updatedAt: "2018-07-03T07:17:52.995Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "51b56a79-4059-4894-b750-02cb84339be6",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T07:23:58.894Z",
                            updatedAt: "2018-07-03T07:23:58.894Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "d5a07e8a-2f81-4643-9650-268859af7b0e",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T08:14:49.553Z",
                            updatedAt: "2018-07-03T08:14:49.553Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "77c1a344-1dc1-4381-b5ab-f450a83cc9c4",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T08:52:30.677Z",
                            updatedAt: "2018-07-03T08:52:30.677Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "f220b0e1-dadc-4c6e-8692-60ef73be4668",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T09:06:39.219Z",
                            updatedAt: "2018-07-03T09:06:39.219Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "427e3c96-40a1-4bac-a189-8174af2b9e02",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T09:14:10.859Z",
                            updatedAt: "2018-07-03T09:14:10.859Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "9d700551-1cbd-46c5-80e1-ed64ec0909e0",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T09:38:57.806Z",
                            updatedAt: "2018-07-03T09:38:57.806Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                          {
                            id: "5c30ac42-fb56-471e-aa79-382bf704744a",
                            review: null,
                            point: null,
                            is_review: false,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            user_id: 4,
                            createdAt: "2018-07-03T09:55:15.930Z",
                            updatedAt: "2018-07-03T09:55:15.930Z",
                            User: {
                              name: "Bhira",
                              avatar_img:
                                "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-user/default.jpg",
                            },
                          },
                        ],
                        Discussions: [
                          {
                            id: "d5b38596-755f-466b-a4b3-2b4dadbd56e1",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "Cek Test 2",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-07-10T06:58:24.565Z",
                            updatedAt: "2018-07-10T06:58:24.565Z",
                          },
                          {
                            id: "7a93a5b3-5f73-4e21-a7b0-56910ab5c5be",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "Test #1 Diskusi",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-07-10T06:30:01.287Z",
                            updatedAt: "2018-07-10T06:30:01.287Z",
                          },
                          {
                            id: "170660c4-e4b7-420d-bfbd-977d7c31e070",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "Test diskusi",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:24:56.058Z",
                            updatedAt: "2018-11-21T03:24:56.058Z",
                          },
                          {
                            id: "09fcf7c0-8d64-4fea-b310-aeeedb4ec109",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "Test Diskusi 2",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:30:36.597Z",
                            updatedAt: "2018-11-21T03:30:36.597Z",
                          },
                          {
                            id: "894fe7c5-f40f-4dea-8eba-798070632450",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "Test Diskusi 3",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:33:05.187Z",
                            updatedAt: "2018-11-21T03:33:05.187Z",
                          },
                          {
                            id: "72cd0d92-4f1f-4c7e-8e49-acb890727a56",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "Test Diskusi 4",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:35:35.125Z",
                            updatedAt: "2018-11-21T03:35:35.125Z",
                          },
                          {
                            id: "f0ad82c4-e2c9-42f3-991d-59277af59a28",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "test diskusi 5",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:37:12.041Z",
                            updatedAt: "2018-11-21T03:37:12.041Z",
                          },
                          {
                            id: "1c16dc35-79f4-4efe-90a9-0e382678011c",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "test diskusi 6",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:43:24.411Z",
                            updatedAt: "2018-11-21T03:43:24.411Z",
                          },
                          {
                            id: "d523eb2f-33ab-47cc-80d2-a09b896b1552",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "test diskusi 7",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:45:51.917Z",
                            updatedAt: "2018-11-21T03:45:51.917Z",
                          },
                          {
                            id: "c28ae8da-747b-406c-aaf5-178be9adbb42",
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            question: "diskusi 10",
                            is_read: null,
                            user_id: 3,
                            is_delete: false,
                            createdAt: "2018-11-21T03:48:50.116Z",
                            updatedAt: "2018-11-21T03:48:50.116Z",
                          },
                        ],
                        Stocks: [
                          {
                            id: 1,
                            warehouse_id: 1,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            qty: 100,
                            Warehouse: {
                              id: 1,
                              name: "Gudang GMP Plasgos",
                              phone_number: "085841410308",
                              address: "Graha Mas Pemuda Blok A No 11, Jati",
                              postal_code: "13220",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2122,
                              is_default: true,
                              store_id: 2,
                              Subdistrict: {
                                id: 2122,
                                name: "Pulo Gadung",
                                type: "Kecamatan",
                                city_id: 154,
                                postal_code: "13240",
                                City: {
                                  id: 154,
                                  name: "Jakarta Timur",
                                  type: "Kota",
                                  postal_code: "13330",
                                  province_id: 6,
                                  Province: {
                                    id: 6,
                                    name: "DKI Jakarta",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 837,
                            warehouse_id: 1,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            qty: 100,
                            Warehouse: {
                              id: 1,
                              name: "Gudang GMP Plasgos",
                              phone_number: "085841410308",
                              address: "Graha Mas Pemuda Blok A No 11, Jati",
                              postal_code: "13220",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2122,
                              is_default: true,
                              store_id: 2,
                              Subdistrict: {
                                id: 2122,
                                name: "Pulo Gadung",
                                type: "Kecamatan",
                                city_id: 154,
                                postal_code: "13240",
                                City: {
                                  id: 154,
                                  name: "Jakarta Timur",
                                  type: "Kota",
                                  postal_code: "13330",
                                  province_id: 6,
                                  Province: {
                                    id: 6,
                                    name: "DKI Jakarta",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2233,
                            warehouse_id: 1044,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            qty: 100,
                            Warehouse: {
                              id: 1044,
                              name: "RANDOM FASHION.ID",
                              phone_number: "6285825684150",
                              address:
                                "Villa tangerang regency 2 blok ab7 no.33, Pasar Kemis, Kabupaten Tangerang, Banten, 15560",
                              postal_code: "15560",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 6287,
                              is_default: false,
                              store_id: 2,
                              Subdistrict: {
                                id: 6287,
                                name: "Pasar Kemis",
                                type: "Kecamatan",
                                city_id: 455,
                                postal_code: "15560",
                                City: {
                                  id: 455,
                                  name: "Tangerang",
                                  type: "Kabupaten",
                                  postal_code: "15914",
                                  province_id: 3,
                                  Province: {
                                    id: 3,
                                    name: "Banten",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2238,
                            warehouse_id: 1045,
                            product_id: "9cdb0e4f-39d5-4fba-a06a-99aa83fa0f05",
                            qty: 100,
                            Warehouse: {
                              id: 1045,
                              name: "EL MEDINAH PONTIANAK",
                              phone_number: "081212677691",
                              address:
                                "An. Maria Kompack 97 / Jl. Sei Raya Dalam Komplek Bhayangkara Permai Blok E.1 No.7 (arah punggur bukan srikandi), Kec. Sungai Raya Sei/Sungai Raya, Kubu Raya, Kalimantan Barat",
                              postal_code: "78391",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2918,
                              is_default: false,
                              store_id: 2,
                              Subdistrict: {
                                id: 2918,
                                name: "Sei/Sungai Raya",
                                type: "Kecamatan",
                                city_id: 208,
                                postal_code: "78391",
                                City: {
                                  id: 208,
                                  name: "Kubu Raya",
                                  type: "Kabupaten",
                                  postal_code: "78311",
                                  province_id: 12,
                                  Province: {
                                    id: 12,
                                    name: "Kalimantan Barat",
                                  },
                                },
                              },
                            },
                          },
                        ],
                      },
                      {
                        id: "20714bdb-4d82-4571-b7f2-c3a9d5f32b37",
                        name: "USB Installer MAC OS Monterey",
                        description:
                          "Install Ulang Bootable Original OS\nbisa dipakai buat upgrade maupun fresh install\n- Flashdisk yang digunakan adalah Sandisk Cruzer Blade berkapasitas 16 GB\n- Flashdisk Lexar JumpDrive Original 16gb\n- Garansi 3 th\nCara Bootable :\nMatikan macbook, Tinggal Colokan Usb Flashdisk dan Hidupkan dengan tekan Option dan POWER bersamaan. otomatis langsung masuk OS.\n\nReady Stock dan Bergaransi bila tidak berfungsi.\nTerima Kasih",
                        subdomain_product: "usb-installer-mac-os-monterey",
                        price: 100000,
                        weight: 200,
                        min_order: 1,
                        status: "active",
                        is_empty: null,
                        condition: "Bekas",
                        is_promoted: false,
                        due_promoted: null,
                        category_id: 20,
                        showcase_id: 1010,
                        store_id: 2,
                        is_visible: false,
                        is_deleted: false,
                        updatedAt: "2024-08-26T10:35:07.383Z",
                        createdAt: "2024-04-19T01:48:48.449Z",
                        GrocierPrices: [],
                        ProductSold: null,
                        ProductViews: [],
                        ProductVolume: {
                          length: 10,
                          width: 8,
                          height: 5,
                        },
                        ImageProducts: [
                          {
                            id: "bd22e4f3-31d3-47b8-ac22-a2a8a3e4e238",
                            url: "https://plasgos.s3.ap-southeast-1.amazonaws.com/product/p_1713491329675_20714bdb-4d82-4571-b7f2-c3a9d5f32b37.png",
                            is_default: true,
                            square_200_url:
                              "https://plasgos.s3.ap-southeast-1.amazonaws.com/img/cache/p/200-square/2024/4/19/p_1713491329675_20714bdb-4d82-4571-b7f2-c3a9d5f32b37.png",
                            square_300_url:
                              "https://plasgos.s3.ap-southeast-1.amazonaws.com/img/cache/p/300-square/2024/4/19/p_1713491329675_20714bdb-4d82-4571-b7f2-c3a9d5f32b37.png",
                          },
                        ],
                        Store: {
                          id: 2,
                          name: "Admin ",
                          description: "Admin Shop penjualan",
                          subdomain_store: "admin-test",
                          avatar_img:
                            "https://image-plasgos.s3-ap-southeast-1.amazonaws.com/avatar-store/default.png",
                          established_year: "2018",
                          business_type: "Importer",
                          number_of_employee: "1-5",
                          is_premium: false,
                          address: "Graha Mas Pemuda Blok A No 11, Jati",
                          latitude: null,
                          longitude: null,
                          postal_code: "13220",
                          due_premium: null,
                          status: "Open",
                          close_from_date: "2018-12-01T17:00:00.000Z",
                          close_to_date: "2019-07-30T17:00:00.000Z",
                          reason_closed: "tutup",
                          user_id: 2,
                          updatedAt: "2025-06-25T04:44:14.206Z",
                          createdAt: "2018-04-27T02:56:58.749Z",
                          city_id: 154,
                          province_id: 6,
                          subdistrict_id: 2122,
                          Province: {
                            id: 6,
                            name: "DKI Jakarta",
                          },
                          City: {
                            id: 154,
                            name: "Jakarta Timur",
                            type: "Kota",
                          },
                          Subdistrict: {
                            id: 2122,
                            name: "Pulo Gadung",
                            type: "Kecamatan",
                            City: {
                              id: 154,
                              name: "Jakarta Timur",
                              type: "Kota",
                              Province: {
                                id: 6,
                                name: "DKI Jakarta",
                              },
                            },
                          },
                          User: {
                            phone_number: "081283598039",
                          },
                        },
                        Category: {
                          id: 20,
                          name: "Software",
                          url: "/c/software",
                        },
                        Showcase: {
                          id: 1010,
                          name: "OS",
                        },
                        Points: [],
                        Discussions: [],
                        Stocks: [
                          {
                            id: 2234,
                            warehouse_id: 1044,
                            product_id: "20714bdb-4d82-4571-b7f2-c3a9d5f32b37",
                            qty: 100,
                            Warehouse: {
                              id: 1044,
                              name: "RANDOM FASHION.ID",
                              phone_number: "6285825684150",
                              address:
                                "Villa tangerang regency 2 blok ab7 no.33, Pasar Kemis, Kabupaten Tangerang, Banten, 15560",
                              postal_code: "15560",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 6287,
                              is_default: false,
                              store_id: 2,
                              Subdistrict: {
                                id: 6287,
                                name: "Pasar Kemis",
                                type: "Kecamatan",
                                city_id: 455,
                                postal_code: "15560",
                                City: {
                                  id: 455,
                                  name: "Tangerang",
                                  type: "Kabupaten",
                                  postal_code: "15914",
                                  province_id: 3,
                                  Province: {
                                    id: 3,
                                    name: "Banten",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2219,
                            warehouse_id: 1,
                            product_id: "20714bdb-4d82-4571-b7f2-c3a9d5f32b37",
                            qty: 1,
                            Warehouse: {
                              id: 1,
                              name: "Gudang GMP Plasgos",
                              phone_number: "085841410308",
                              address: "Graha Mas Pemuda Blok A No 11, Jati",
                              postal_code: "13220",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2122,
                              is_default: true,
                              store_id: 2,
                              Subdistrict: {
                                id: 2122,
                                name: "Pulo Gadung",
                                type: "Kecamatan",
                                city_id: 154,
                                postal_code: "13240",
                                City: {
                                  id: 154,
                                  name: "Jakarta Timur",
                                  type: "Kota",
                                  postal_code: "13330",
                                  province_id: 6,
                                  Province: {
                                    id: 6,
                                    name: "DKI Jakarta",
                                  },
                                },
                              },
                            },
                          },
                          {
                            id: 2239,
                            warehouse_id: 1045,
                            product_id: "20714bdb-4d82-4571-b7f2-c3a9d5f32b37",
                            qty: 100,
                            Warehouse: {
                              id: 1045,
                              name: "EL MEDINAH PONTIANAK",
                              phone_number: "081212677691",
                              address:
                                "An. Maria Kompack 97 / Jl. Sei Raya Dalam Komplek Bhayangkara Permai Blok E.1 No.7 (arah punggur bukan srikandi), Kec. Sungai Raya Sei/Sungai Raya, Kubu Raya, Kalimantan Barat",
                              postal_code: "78391",
                              latitude: null,
                              longitude: null,
                              subdistrict_id: 2918,
                              is_default: false,
                              store_id: 2,
                              Subdistrict: {
                                id: 2918,
                                name: "Sei/Sungai Raya",
                                type: "Kecamatan",
                                city_id: 208,
                                postal_code: "78391",
                                City: {
                                  id: 208,
                                  name: "Kubu Raya",
                                  type: "Kabupaten",
                                  postal_code: "78311",
                                  province_id: 12,
                                  Province: {
                                    id: 12,
                                    name: "Kalimantan Barat",
                                  },
                                },
                              },
                            },
                          },
                        ],
                      },
                    ],
                    settings: {
                      isShowProducts: true,
                      label: "Pilih Produk",
                      isAllowMultipleQuantities: true,
                      isShowPrice: true,
                      isShowImage: true,
                      isShowDescription: true,
                    },
                  },
                  submitEvent: {
                    event: "instruction_page",
                    contentTemplateCOD:
                      '<p style="text-align: center"><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem)"><strong>Terima kasih  sudah melakukan order</strong></span><br><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem); color: rgb(74, 144, 226)"><strong> </strong></span><span style="font-family: Montserrat; font-size: clamp(1rem, 1.5vw, 1.125rem); color: rgb(74, 144, 226)"><strong>{{product_name}} </strong></span><br><br>Pesanan Anda sedang kami proses. <br>📦 Kurir akan mengantarkan pesanan dalam <strong>2–4 hari ke depan</strong>. <strong><br></strong><br>Mohon siapkan pembayaran sebesar:<br><br><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem); color: rgb(74, 144, 226)"><strong>{{total_price}}</strong></span><br><br>Pembayaran dilakukan <strong>langsung kepada kurir saat pesanan diterima</strong> <br><br>Terima kasih telah berbelanja bersama kami.</p><p>Semoga Anda puas dengan produk kami!</p>',
                    contentTemplateBankTransfer:
                      '<p style="text-align: center"><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem)"><strong>Terima kasih sudah melakukan order</strong></span><br><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem); color: rgb(74, 144, 226)"><strong> </strong></span><span style="font-family: Montserrat; font-size: clamp(1rem, 1.5vw, 1.125rem); color: rgb(74, 144, 226)"><strong>{{product_name}} </strong></span><br>Pesanan Anda sedang kami proses. <br>📦 Kurir akan mengantarkan pesanan dalam <strong>2–4 hari ke depan</strong>. <strong><br></strong><br>Mohon siapkan pembayaran sebesar:<br><br><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem); color: rgb(74, 144, 226)"><strong>{{total_price}}</strong></span><br><br>Pembayaran dilakukan <strong>langsung kepada kurir saat pesanan diterima</strong> <br><br>Terima kasih telah berbelanja bersama kami.</p><p>Semoga Anda puas dengan produk kami!</p>',
                    contentTemplateEpayment:
                      '<p style="text-align: center"><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem)"><strong>Terima kasih sudah melakukan order</strong></span><br><span style="font-family: Montserrat; font-size: clamp(1.125rem, 2vw, 1.25rem); color: rgb(74, 144, 226)"><strong> </strong></span><span style="font-family: Montserrat; font-size: clamp(1rem, 1.5vw, 1.125rem); color: rgb(74, 144, 226)"><strong>{{product_name}} </strong></span><br><br>Untuk menyelesaikan pembayaran, silakan transfer sejumlah: <br><br><span style="font-family: &quot;Open Sans&quot;; color: rgb(74, 144, 226)"><strong>{{total_price}} </strong></span><br><br>{{payment_options}} <br><br><span style="font-size: clamp(0.75rem, 1vw, 0.875rem)">Setelah melakukan transfer, jangan lupa untuk melakukan konfirmasi agar pesanan Anda segera kami proses:</span></p>',
                    sendingEmailInvoice: true,
                    chatTemplateId: "bankTransfer",
                    waChatTemplate:
                      "Halo, saya sudah menyelesaikan pemesanan untuk { items_name } atas nama { name } dan akan melakukan pembayaran melalui transfer bank. Mohon bantuannya untuk segera diproses. Terima kasih! 🙏",
                    pixels: {
                      facebook_pixel: {
                        ids: [],
                        events: [
                          {
                            name: "InitialCheckout",
                          },
                        ],
                      },
                      tiktok_pixel: {
                        ids: [],
                        events: [
                          {
                            name: "InitialCheckout",
                          },
                        ],
                      },
                    },
                  },
                  wrapperStyle: {
                    width: 500,
                    titleSize: 24,
                    titleColor: "rgba(0, 0, 0, 1)",
                    labelSize: 14,
                    labelColor: "rgba(0, 0, 0, 1)",
                    inputColor: "rgba(255, 255, 255, 1)",
                    inputSize: 14,
                    textInputColor: "rgba(0, 0, 0, 1)",
                    borderColor: "rgba(115, 115, 115, 0.5)",
                    rounded: 8,
                    space: 20,
                    buttonText: "Beli Sekarang",
                    buttonColor: "rgba(250, 84, 28,1)",
                    iconBtn: {
                      icon: "",
                      color: "",
                      size: 24,
                      position: "right",
                    },
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    isFullWidth: true,
                  },
                },
                isFromAI: false,
              },
            ],
            head: {
              type: "head",
            },
            docEl: {
              tagName: "html",
            },
          },
          id: "V59lnmC0FniftWp0",
        },
      ],
      type: "main",
      id: "61QBUFYqDo2QYKmO",
    },
  ],
  symbols: [],
  dataSources: [],
  globalOptions: {
    maxWidthPage: 1360,
    schemeColor: null,
    bgColor: "",
    scrollTarget: [
      {
        id: "target-01",
        value: "scrollToTop",
        label: "Scroll To Top",
      },
    ],
    isFocusContent: "",
    isOutlineActive: true,
    watermark: true,
    isSubscribed: true,
  },
  popups: [],
};
export default function Home() {
  return <RenderViewComponent publishData={publishData} />;
}
