import RenderViewComponent from "@/components/RenderViewComponent";

const publishData = {
  assets: [],
  styles: [],
  pages: [
    {
      frames: [
        {
          component: {
            type: "wrapper",
            stylable: "",
            highlightable: false,
            hoverable: false,
            components: [
              {
                type: "text-element",
                draggable: false,
                attributes: {
                  id: "iltyu",
                },
                customComponent: {
                  contents: [
                    {
                      id: "text-uj28xb5il",
                      textShadow: null,
                      shadowColor: "",
                      text: '<p><span style="font-family: Raleway; font-size: clamp(2.25rem, 5vw, 3rem); color: rgb(0, 0, 0)"><strong><em>The quick brown fox jumps over the lazy dog</em></strong></span></p><p><span style="font-family: Raleway; font-size: clamp(2.25rem, 5vw, 3rem); color: rgb(0, 0, 0)"><strong><em>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Nobis numquam expedita molestiae accusamus, adipisci magnam. Cupiditate, autem dolore! Libero nisi harum assumenda molestiae officia blanditiis reprehenderit hic dolore iste inventore!</em></strong></span></p>',
                      textColor: "",
                      rotation: 0,
                      alignText: "justify-center",
                    },
                  ],
                  typeSuggestion: "heading",
                  textPrompt: "",
                  smartTextSuggestions: [],
                },
                isFromAI: false,
              },
              {
                type: "navbar",
                draggable: false,
                attributes: {
                  id: "imahu",
                },
                customComponent: {
                  contents: [
                    {
                      id: "single-link-l4am73npx",
                      type: "single-link",
                      label: "Single Link",
                      icon: {
                        key: null,
                        ref: null,
                        props: {},
                        _owner: null,
                        _store: {},
                      },
                      target: {
                        actionType: "link",
                        options: {
                          type: null,
                        },
                      },
                      titleHeading: "About",
                      iconHeading: {
                        icon: "",
                        color: "",
                        size: 24,
                        position: "left",
                      },
                    },
                    {
                      id: "menu-link-qimq62bqc",
                      type: "menu-link",
                      label: "Menu Link",
                      icon: {
                        key: null,
                        ref: null,
                        props: {},
                        _owner: null,
                        _store: {},
                      },
                      options: [
                        {
                          label: "Alert Dialog",
                          href: "/docs/primitives/alert-dialog",
                          description:
                            "A modal dialog that interrupts the user with important content and expects a response.",
                          id: "menu-0-cw1bs8cka",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Hover Card",
                          href: "/docs/primitives/hover-card",
                          description:
                            "For sighted users to preview content available behind a link.",
                          id: "menu-1-l9r50flx8",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Progress",
                          href: "/docs/primitives/progress",
                          description:
                            "Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.",
                          id: "menu-2-zqrfqiezg",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Scroll-area",
                          href: "/docs/primitives/scroll-area",
                          description:
                            "Visually or semantically separates content.",
                          id: "menu-3-11279c9pg",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Tabs",
                          href: "/docs/primitives/tabs",
                          description:
                            "A set of layered sections of content—known as tab panels—that are displayed one at a time.",
                          id: "menu-4-sm80580s5",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Tooltip",
                          href: "/docs/primitives/tooltip",
                          description:
                            "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.",
                          id: "menu-5-amwom2mde",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                      ],
                      titleHeading: "Component Menu",
                      column: "2",
                      iconHeading: {
                        icon: "",
                        color: "",
                        size: 24,
                        position: "left",
                      },
                    },
                    {
                      id: "menu-link-02-gnhshn6sm",
                      type: "menu-link",
                      label: "Menu Link",
                      icon: {
                        key: null,
                        ref: null,
                        props: {},
                        _owner: null,
                        _store: {},
                      },
                      options: [
                        {
                          label: "Alert Dialog",
                          href: "/docs/primitives/alert-dialog",
                          description: "",
                          id: "menu-0-h1psc971b",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Hover Card",
                          href: "/docs/primitives/hover-card",
                          description: "",
                          id: "menu-1-l0262paa0",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Progress",
                          href: "/docs/primitives/progress",
                          description: "",
                          id: "menu-2-mqyp5vrdv",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Scroll-area",
                          href: "/docs/primitives/scroll-area",
                          description: "",
                          id: "menu-3-0tdvsiw4z",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Tabs",
                          href: "/docs/primitives/tabs",
                          description: "",
                          id: "menu-4-jtzlw1orm",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                        {
                          label: "Tooltip",
                          href: "/docs/primitives/tooltip",
                          description: "",
                          id: "menu-5-zuktd7t18",
                          target: {
                            actionType: "link",
                            options: {
                              type: null,
                            },
                          },
                        },
                      ],
                      titleHeading: "Component Single Menu",
                      column: "1",
                      iconHeading: {
                        icon: "",
                        color: "",
                        size: 24,
                        position: "left",
                      },
                    },
                  ],
                  wrapperStyle: {
                    headingColor: "",
                    headingFontSize: "clamp(1rem, 1.5vw, 1.125rem)",
                    fontWeight: 900,
                    fontFamily: "Roboto",
                    isItalicHeader: true,
                    description: {
                      descriptionColor: "",
                      fontWeight: 900,
                      fontFamily: "Roboto",
                      isItalicDescription: true,
                    },
                    menuBgColor: "",
                    bgColorSidebar: "",
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: true,
                  },
                  logo: "https://ik.imagekit.io/ez1ffaf6o/default-images/plg-logo.png?updatedAt=1747224274623",
                  logoWidth: 150,
                  side: "right",
                },
                isFromAI: false,
              },
              {
                type: "split-text",
                draggable: false,
                attributes: {
                  id: "iszw",
                },
                customComponent: {
                  isLocked: false,
                  text: "Hello World!",
                  fontFamily: "Roboto",
                  fontWeight: 900,
                  colorSplitText: "rgba(0, 0, 0, 1)",
                  delay: 150,
                  textAlign: "text-center",
                  fontSize: "clamp(1.125rem, 2vw, 1.25rem)",
                  contents: [],
                  isItalicHeader: true,
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "button-element",
                draggable: false,
                attributes: {
                  id: "iw1nk",
                },
                customComponent: {
                  isLocked: false,
                  buttons: [
                    {
                      id: "button-01",
                      stylesBtn: {
                        title: "Get Started",
                        btnColor: "rgba(74,144,226,100)",
                        textColor: "rgba(255,255,255,100)",
                        size: "default",
                        variant: "default",
                        rounded: 10,
                        shadow: "",
                      },
                      iconBtn: {
                        icon: "",
                        color: "",
                        size: 24,
                        position: "right",
                      },
                      target: {
                        actionType: "link",
                        options: {
                          type: null,
                        },
                      },
                    },
                  ],
                  mainStyle: {
                    space: 20,
                    position: "flex-row",
                    align: "justify-center",
                    shadow: "shadow",
                  },
                },
                isFromAI: false,
              },
              {
                type: "faq",
                draggable: false,
                attributes: {
                  id: "i5376",
                },
                customComponent: {
                  contents: [
                    {
                      id: "faq-01",
                      title: "Berapa lama waktu pengiriman?",
                      description:
                        "Waktu pengiriman berkisar antara 1-3 hari kerja, tergantung pada lokasi tujuan.",
                    },
                    {
                      id: "faq-02",
                      title: "Apakah ada biaya pengiriman?",
                      description:
                        "Gratis ongkos kirim untuk semua pesanan di atas Rp 200.000 ke seluruh Indonesia.",
                    },
                    {
                      id: "faq-03",
                      title: "Bagaimana jika barang rusak saat diterima?",
                      description:
                        "Segera hubungi tim kami dalam 24 jam dengan melampirkan foto barang rusak untuk proses pengembalian atau penggantian.",
                    },
                    {
                      id: "faq-04",
                      title: "Apakah bisa melakukan pengembalian barang?",
                      description:
                        "Ya, Anda dapat mengembalikan barang dalam kondisi belum digunakan dalam waktu 7 hari setelah penerimaan.",
                    },
                  ],
                  wrapperStyle: {
                    variant: "basic",
                    colorTitle: "",
                    fontWeight: 900,
                    fontFamily: "Roboto",
                    fontSize: "clamp(1rem, 1.5vw, 1.125rem)",
                    textAligment: "justify-center",
                    borderColor: "rgba(115, 115, 115, 0.5)",
                    iconColor: "rgb(46, 30, 24,1)",
                    isItalicHeader: true,
                    descriptionColor: "rgba(255,205,210,1)",
                    descriptionFontWeight: 900,
                    descriptionFontFamily: "Playfair Display",
                    descriptionFontSize: "clamp(0.875rem, 1.2vw, 1rem)",
                    isItalicDescription: true,
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "feature-highlights",
                draggable: false,
                attributes: {
                  id: "ij8mg",
                },
                customComponent: {
                  contents: [
                    {
                      id: "feature-01",
                      title: "Rasakan Bedanya dalam Satu Sentuhan!",
                      iconBtn: {
                        icon: "FaCheckCircle",
                        color: "rgba(126,211,33,1)",
                        size: 24,
                        position: "left",
                      },
                    },
                    {
                      id: "feature-02",
                      title: "Inovasi Terbaru untuk Keseharian Anda.",
                      iconBtn: {
                        icon: "FaCheckCircle",
                        color: "rgba(126,211,33,1)",
                        size: 24,
                        position: "left",
                      },
                    },
                    {
                      id: "feature-03",
                      title: "Solusi Cerdas untuk Hidup Lebih Nyaman.",
                      iconBtn: {
                        icon: "FaCheckCircle",
                        color: "rgba(126,211,33,1)",
                        size: 24,
                        position: "left",
                      },
                    },
                    {
                      id: "feature-04",
                      title: "Transformasi Mudah, Hasil Maksimal.",
                      iconBtn: {
                        icon: "FaCheckCircle",
                        color: "rgba(126,211,33,1)",
                        size: 24,
                        position: "left",
                      },
                    },
                  ],
                  wrapperStyle: {
                    space: 20,
                    textShadow: null,
                    titleColor: "",
                    fontWeight: 700,
                    fontFamily: "Roboto",
                    fontSize: "clamp(1rem, 1.5vw, 1.125rem)",
                    textAligment: "justify-center",
                    isItalicHeader: false,
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                  animation: {
                    type: null,
                    duration: 1,
                    delay: null,
                    isReplay: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "blur-text",
                draggable: false,
                attributes: {
                  id: "iq2n",
                },
                customComponent: {
                  isLocked: false,
                  text: "Isn't this so cool?!",
                  fontFamily: "Open Sans",
                  fontWeight: 800,
                  colorBlurText: "rgba(0, 0, 0, 1)",
                  delay: 200,
                  textAlign: "justify-center",
                  fontSize: 36,
                  animateBy: "words",
                  direction: "top",
                  contents: [],
                  isItalicHeader: true,
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "business-overview",
                draggable: false,
                attributes: {
                  id: "ijgdb",
                },
                customComponent: {
                  isLocked: false,
                  contents: [
                    {
                      id: "7kabhqhdi",
                      overview: "Products",
                      from: 0,
                      rangeValue: 100,
                      symbol: "+",
                    },
                    {
                      id: "v3ra4p74s",
                      overview: "Monthly Orders",
                      from: 0,
                      rangeValue: 2500,
                      symbol: "+",
                    },
                    {
                      id: "lnj3fljmj",
                      overview: "Happy Customer",
                      from: 0,
                      rangeValue: 100,
                      symbol: "%",
                    },
                  ],
                  wrapperStyle: {
                    separator: ",",
                    direction: "up",
                    duration: 1,
                    colorRangeValue: "rgba(0, 0, 0, 1)",
                    textAligment: "justify-center",
                    fontSize: 36,
                    fontFamily: "Roboto",
                    fontWeight: 500,
                    textShadow: null,
                    distance: 100,
                    isItalicHeader: true,
                    fontSizeOverview: 16,
                    fontFamilyOverview: "Roboto",
                    fontWeightOverview: 500,
                    colorOverview: "rgba(0, 0, 0, 1)",
                    isItalicOverview: true,
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "testimony",
                draggable: false,
                attributes: {
                  id: "i50dj",
                },
                customComponent: {
                  contents: [
                    {
                      id: "testimony-01",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/avatar3.jpg?updatedAt=1747122493693",
                      name: "John",
                      profetion: "Designer",
                      description:
                        "Waktu pengiriman berkisar antara 1-3 hari kerja, tergantung pada lokasi tujuan.",
                      stars: 3,
                    },
                    {
                      id: "testimony-02",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/avatar2.jpg?updatedAt=1747122493339",
                      name: "Emily",
                      profetion: "Developer",
                      description:
                        "Produk berkualitas dan layanan pelanggan yang sangat responsif!",
                      stars: 4,
                    },
                    {
                      id: "testimony-03",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/avatar1.jpg?updatedAt=1747122493302",
                      name: "Michael",
                      profetion: "Entrepreneur",
                      description:
                        "Sangat puas dengan pengalaman belanja di sini, akan kembali lagi!",
                      stars: 5,
                    },
                    {
                      id: "testimony-04",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/avatar4.jpg?updatedAt=1747122493268",
                      name: "Sophia",
                      profetion: "Marketing ",
                      description:
                        "Pengiriman cepat dan barang sesuai dengan deskripsi. Sangat direkomendasikan!",
                      stars: 5,
                    },
                    {
                      id: "testimony-05",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/avatar6.jpg?updatedAt=1747122493203",
                      name: "Elena",
                      profetion: "Freelance",
                      description:
                        "Saya sangat puas dengan produk ini! Kualitasnya luar biasa dan sesuai dengan ekspektasi saya. Pengiriman juga cepat dan pelayanannya ramah.",
                      stars: 5,
                    },
                  ],
                  wrapperStyle: {
                    variant: "1",
                    nameColor: "",
                    fontWeight: 900,
                    fontFamily: "Lato",
                    fontSize: 18,
                    textAligment: "text-center",
                    borderColor: "rgba(223, 221, 221, 1)",
                    cardColor: "transparent",
                    quoteColor: "rgba(245, 245, 245, 1)",
                    profectionColor: "rgba(148, 148, 150, 1)",
                    starsColor: "rgba(255,210,80,1)",
                    starsSize: 20,
                    withSlider: true,
                    autoPlaySlider: false,
                    isItalicHeader: true,
                    descriptionColor: "",
                    descriptionFontWeight: 800,
                    descriptionFontFamily: "Urbanist",
                    descriptionFontSize: "clamp(0.875rem, 1.2vw, 1rem)",
                    isItalicDescription: true,
                    header:
                      '<p style="text-align: center"><span style="font-family: Fugaz One; font-size: 26px">Testimonials</span></p><p style="text-align: center"><span style="font-family: Style Script; font-size: 40px">What our clients saya about us</span></p>',
                    headerColor: "",
                    textShadow: null,
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "content-showcase",
                draggable: false,
                attributes: {
                  id: "i3emj",
                },
                customComponent: {
                  isLocked: false,
                  contents: [
                    {
                      id: "lyemsn2nd",
                      title: "Panduan Lengkap Memulai Bisnis Online",
                      description:
                        "Temukan langkah-langkah praktis memulai bisnis online dari nol. Pelajari strategi pemasaran, manajemen produk, dan tips meningkatkan penjualan secara efekti",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/products1.webp?updatedAt=1747115975853",
                      target: {
                        actionType: "link",
                        options: {
                          isOpenNewTab: true,
                          link: "https://www.youtube.com/",
                          type: "url",
                        },
                      },
                    },
                    {
                      id: "7abhojep8",
                      title: "Tips Meningkatkan Kualitas Produk Anda",
                      description:
                        "Pelajari cara meningkatkan kualitas produk Anda dengan bahan terbaik dan proses produksi yang efisien. Dapatkan kepercayaan pelanggan dan tingkatkan loyalitas merek.",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/products2.webp?updatedAt=1747115975781",
                      target: {
                        actionType: "link",
                        options: {
                          type: null,
                        },
                      },
                    },
                    {
                      id: "bralxt2jk",
                      title: "Langkah Menciptakan Produk Inovatif",
                      description:
                        "Ketahui langkah-langkah menciptakan produk inovatif yang memenuhi kebutuhan pasar. Mulai dari riset hingga peluncuran, raih peluang bisnis yang lebih besar.",
                      image:
                        "https://ik.imagekit.io/ez1ffaf6o/default-images/products4.jpg?updatedAt=1747115975342",
                      target: {
                        actionType: "link",
                        options: {
                          type: null,
                        },
                      },
                    },
                  ],
                  wrapperStyle: {
                    column: "3",
                    aspectRatio: 0.8,
                    rounded: 20,
                    titleColor: "",
                    fontWeight: 700,
                    imagePosition: "center",
                    fontFamily: "Arvo",
                    fontSize: "clamp(1.125rem, 2vw, 1.25rem)",
                    textAligment: "text-center",
                    isItalicHeader: true,
                    descriptionColor: "",
                    descriptionFontWeight: 900,
                    descriptionFontFamily: "Mulish",
                    descriptionFontSize: "clamp(0.875rem, 1.2vw, 1rem)",
                    textAligmentDescription: "text-center",
                    isItalicDescription: true,
                  },
                  background: {
                    bgType: null,
                    bgColor: "",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "fuzzy-text",
                draggable: false,
                attributes: {
                  id: "iy0uo",
                },
                customComponent: {
                  isLocked: false,
                  text: "404",
                  fontFamily: "Bebas Neue",
                  fontWeight: 400,
                  colorFuzzyText: "rgba(255, 255, 255, 1)",
                  textAlign: "justify-center",
                  fontSize: 120,
                  hoverIntensity: 0.5,
                  baseIntensity: 0.2,
                  enableHover: true,
                  contents: [],
                  isItalicHeader: false,
                  background: {
                    bgType: "bgColor",
                    bgColor: "rgba(0, 0, 0, 1)",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "glitch-text",
                draggable: false,
                attributes: {
                  id: "i6xps",
                },
                customComponent: {
                  isLocked: false,
                  text: "Plasgos",
                  fontFamily: "Merriweather",
                  fontWeight: 900,
                  colorGlitchText: "rgba(255, 255, 255, 1)",
                  textAlign: "justify-center",
                  fontSize: 120,
                  speed: 5,
                  enableHover: true,
                  enableShadows: true,
                  enableOnHover: false,
                  contents: [],
                  isItalicHeader: true,
                  background: {
                    bgType: "bgColor",
                    bgColor: "rgba(6, 6, 6, 1)",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
              {
                type: "scroll-velocity-text",
                draggable: false,
                attributes: {
                  id: "ie62z",
                },
                customComponent: {
                  isLocked: false,
                  fontFamily: "Alegreya",
                  fontWeight: 900,
                  colorVelocity: "rgba(255, 255, 255, 1)",
                  textAlign: "justify-center",
                  fontSize: 80,
                  velocity: 100,
                  contents: [
                    {
                      id: "text-01-xrfm4xok1",
                      title: "Plasgos Web",
                    },
                    {
                      id: "text-02-o14zxcd69",
                      title: "Scroll Down",
                    },
                  ],
                  isItalicHeader: true,
                  background: {
                    bgType: "bgColor",
                    bgColor: "rgba(0, 0, 0, 1)",
                    bgImage: "",
                    blur: 0,
                    opacity: 0,
                    padding: 0,
                    marginTop: 0,
                    marginBottom: 0,
                    direction: "to right",
                    fromColor: "",
                    toColor: "",
                    isRevert: false,
                    pattern: "",
                    rounded: 0,
                    isFullWidth: false,
                  },
                },
                isFromAI: false,
              },
            ],
            head: {
              type: "head",
            },
            docEl: {
              tagName: "html",
            },
          },
          id: "WNfypBTbuQRx5pZI",
        },
      ],
      type: "main",
      id: "lAZ9QLdYedmbewZC",
    },
  ],
  symbols: [],
  dataSources: [],
  globalOptions: {
    maxWidthPage: 1360,
    schemeColor: null,
    bgColor: "",
    scrollTarget: [
      {
        id: "target-01",
        value: "scrollToTop",
        label: "Scroll To Top",
      },
    ],
    isFocusContent: "",
    isOutlineActive: true,
    watermark: true,
    isSubscribed: true,
  },
  popups: [],
};
export default function Home() {
  return <RenderViewComponent publishData={publishData} />;
}
